//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thwartski_Hud_Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thwartski_Hud_Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap aspectImageNormal {
            get {
                object obj = ResourceManager.GetObject("aspectImageNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aspectImageWidescreen {
            get {
                object obj = ResourceManager.GetObject("aspectImageWidescreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mainMenuImage {
            get {
                object obj = ResourceManager.GetObject("mainMenuImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scoreboardImageComp6 {
            get {
                object obj = ResourceManager.GetObject("scoreboardImageComp6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scoreboardImageComp9 {
            get {
                object obj = ResourceManager.GetObject("scoreboardImageComp9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scoreboardImagePub24 {
            get {
                object obj = ResourceManager.GetObject("scoreboardImagePub24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scoreboardImagePub32 {
            get {
                object obj = ResourceManager.GetObject("scoreboardImagePub32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Hud.
        /// </summary>
        internal static string stringButtonInstallFreshMode {
            get {
                return ResourceManager.GetString("stringButtonInstallFreshMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch TF2.
        /// </summary>
        internal static string stringButtonInstallLaunchMode {
            get {
                return ResourceManager.GetString("stringButtonInstallLaunchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Options.
        /// </summary>
        internal static string stringButtonInstallOptionsMode {
            get {
                return ResourceManager.GetString("stringButtonInstallOptionsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string stringComboboxAspectNormal {
            get {
                return ResourceManager.GetString("stringComboboxAspectNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widescreen.
        /// </summary>
        internal static string stringComboboxAspectWidescreen {
            get {
                return ResourceManager.GetString("stringComboboxAspectWidescreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6v6.
        /// </summary>
        internal static string stringComboboxScoreboardComp6 {
            get {
                return ResourceManager.GetString("stringComboboxScoreboardComp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlander.
        /// </summary>
        internal static string stringComboboxScoreboardComp9 {
            get {
                return ResourceManager.GetString("stringComboboxScoreboardComp9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 Player.
        /// </summary>
        internal static string stringComboboxScoreboardPub24 {
            get {
                return ResourceManager.GetString("stringComboboxScoreboardPub24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 Player.
        /// </summary>
        internal static string stringComboboxScoreboardPub32 {
            get {
                return ResourceManager.GetString("stringComboboxScoreboardPub32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpectatorTournament_Normal.res.
        /// </summary>
        internal static string stringFilenameAssetAspectNormal {
            get {
                return ResourceManager.GetString("stringFilenameAssetAspectNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpectatorTournament_Widescreen.res.
        /// </summary>
        internal static string stringFilenameAssetAspectWidescreen {
            get {
                return ResourceManager.GetString("stringFilenameAssetAspectWidescreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameMenu_Pub24Comp6.res.
        /// </summary>
        internal static string stringFilenameAssetMenuComp6Pub24 {
            get {
                return ResourceManager.GetString("stringFilenameAssetMenuComp6Pub24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameMenu_Pub32Comp6.res.
        /// </summary>
        internal static string stringFilenameAssetMenuComp6Pub32 {
            get {
                return ResourceManager.GetString("stringFilenameAssetMenuComp6Pub32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameMenu_Pub24Comp9.res.
        /// </summary>
        internal static string stringFilenameAssetMenuComp9Pub24 {
            get {
                return ResourceManager.GetString("stringFilenameAssetMenuComp9Pub24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameMenu_Pub32Comp9.res.
        /// </summary>
        internal static string stringFilenameAssetMenuComp9Pub32 {
            get {
                return ResourceManager.GetString("stringFilenameAssetMenuComp9Pub32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreBoard_Pub24Comp6.res.
        /// </summary>
        internal static string stringFilenameAssetScoreboardComp6Pub24 {
            get {
                return ResourceManager.GetString("stringFilenameAssetScoreboardComp6Pub24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreBoard_Pub32Comp6.res.
        /// </summary>
        internal static string stringFilenameAssetScoreboardComp6Pub32 {
            get {
                return ResourceManager.GetString("stringFilenameAssetScoreboardComp6Pub32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreBoard_Pub24Comp9.res.
        /// </summary>
        internal static string stringFilenameAssetScoreboardComp9Pub24 {
            get {
                return ResourceManager.GetString("stringFilenameAssetScoreboardComp9Pub24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreBoard_Pub32Comp9.res.
        /// </summary>
        internal static string stringFilenameAssetScoreboardComp9Pub32 {
            get {
                return ResourceManager.GetString("stringFilenameAssetScoreboardComp9Pub32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpectatorTournament.res.
        /// </summary>
        internal static string stringFilenameInstallAspect {
            get {
                return ResourceManager.GetString("stringFilenameInstallAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameMenu.res.
        /// </summary>
        internal static string stringFilenameInstallMenu {
            get {
                return ResourceManager.GetString("stringFilenameInstallMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreBoard.res.
        /// </summary>
        internal static string stringFilenameInstallScoreboard {
            get {
                return ResourceManager.GetString("stringFilenameInstallScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thwartski Hud Installed.txt.
        /// </summary>
        internal static string stringFilenameInstallVersion {
            get {
                return ResourceManager.GetString("stringFilenameInstallVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetFiles.zip.
        /// </summary>
        internal static string stringFilenameZipfile {
            get {
                return ResourceManager.GetString("stringFilenameZipfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thwartski Hud Assets\.
        /// </summary>
        internal static string stringFolderAsset {
            get {
                return ResourceManager.GetString("stringFolderAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _HUD BACKUPS\.
        /// </summary>
        internal static string stringFolderBackup {
            get {
                return ResourceManager.GetString("stringFolderBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Thwartski Hud Options\.
        /// </summary>
        internal static string stringFolderOptions {
            get {
                return ResourceManager.GetString("stringFolderOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource\.
        /// </summary>
        internal static string stringFolderResource {
            get {
                return ResourceManager.GetString("stringFolderResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Steam\steamapps\.
        /// </summary>
        internal static string stringFolderSteamapps32Bit {
            get {
                return ResourceManager.GetString("stringFolderSteamapps32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Steam\steamapps\.
        /// </summary>
        internal static string stringFolderSteamapps64Bit {
            get {
                return ResourceManager.GetString("stringFolderSteamapps64Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \YOUR_STEAM_FOLDER\steamapps\.
        /// </summary>
        internal static string stringFolderSteamappsUnknown {
            get {
                return ResourceManager.GetString("stringFolderSteamappsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR_USERNAME.
        /// </summary>
        internal static string stringFolderSteamUserUnknown {
            get {
                return ResourceManager.GetString("stringFolderSteamUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \team fortress 2.
        /// </summary>
        internal static string stringFolderTeamFortress2 {
            get {
                return ResourceManager.GetString("stringFolderTeamFortress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tf\.
        /// </summary>
        internal static string stringFolderTf {
            get {
                return ResourceManager.GetString("stringFolderTf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui\.
        /// </summary>
        internal static string stringFolderUi {
            get {
                return ResourceManager.GetString("stringFolderUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All hud files are now reverted to Valve defaults..
        /// </summary>
        internal static string stringMessageUninstallComplete {
            get {
                return ResourceManager.GetString("stringMessageUninstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your custom options have been installed..
        /// </summary>
        internal static string stringMessageUpdateSettingsComplete {
            get {
                return ResourceManager.GetString("stringMessageUpdateSettingsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam://rungameid/440.
        /// </summary>
        internal static string stringTeamFortressLaunchCommand {
            get {
                return ResourceManager.GetString("stringTeamFortressLaunchCommand", resourceCulture);
            }
        }
    }
}
